CREATE CONSTRAINT paper_id IF NOT EXISTS
FOR (p:Paper)
REQUIRE p.id IS UNIQUE;

CREATE CONSTRAINT method_id IF NOT EXISTS
FOR (m:Method)
REQUIRE m.id IS UNIQUE;

CREATE CONSTRAINT entity_id IF NOT EXISTS
FOR (e:Entity)
REQUIRE e.id IS UNIQUE;

CREATE CONSTRAINT claim_id IF NOT EXISTS
FOR (c:Claim)
REQUIRE c.id IS UNIQUE;

CREATE CONSTRAINT hypothesis_seed_id IF NOT EXISTS
FOR (h:HypothesisSeed)
REQUIRE h.id IS UNIQUE;
